name: pozadkey_v3
description: "Pozadkey â€“ Software & Systems Engineer"
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_strategy: ^0.3.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.16
  intl: ^0.20.1
  dotted_border: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono/GeistMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/GeistMono/GeistMono-ExtraBold.ttf
          weight: 800

